# Site settings
title: "Neulich im Netz"
description: "Der Internet-Podcast"
podcast-description: "Neulich im Netz - der Internet-Podcast. Alle 14 Tage ein Thema aus dem Bereich Internet-Technologien, Protokolle und Ph채nomene."
url:  "https://neulich-im-netz.github.io" # Actual base url of the website
baseurl: "/"                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Rolf Winter und Dirk Kutscher"
  # email: "alessiofranceschi2@gmail.com"
  # url: "https://alessiofranceschi.me"
permalink: pretty
permalink: /:title
keywords: [podcast, Neulich im Netz, Internet-Podcast]

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

#exclude: [_podcast.rss] #Ignore this, it will be used in case I decide to add rss feed

#Pagination
paginate: 5
paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO
twitter:
  username: NeulichInternet
  card: summary
# facebook:
#  app_id: 
logo: /assets/img/Podcast_Cover.png
social:
  name: Neulich im Netz
  links:
    - https://twitter.com/NeulichInternet
lang: de

#Podcast Metadata. Used by the RSS Feed, which currently isn't in use. So you can avoid this
podcast_title: Neulich im Netz
podcast_author: Rolf Winter und Dirk Kutscher
# podcast_email: alessiofranceschi2@gmail.com
podcast_subtitle: "Der Internet-Podcast"
podcast_summary: "Alle 14 Tage ein Thema aus dem Bereich Internet-Technologien, Protokolle und Ph채nomene."
podcast_description: "Neulich im Netz - der Internet-Podcast. Wir reden alle 14 Tage 체ber ein Thema aus dem Bereich Internet-Technologien, Protokolle und Ph채nomene."
podcast_explicit: "no"
podcast_type: serial 
podcast_lang: de
podcast_launch: "2021-05-05" #Launch date of your podcast
podcast_copyright: "&#xA9;Rolf Winter und Dirk Kutscher"
podcast_feed: 
podcast_artwork: "/assets/img/Podcast_Cover.png"
